# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-02 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form01', '0003_auto_20180502_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
