# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-03 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tamll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tmal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, null=True)),
                ('subtitle', models.CharField(default='都是好东西', max_length=255)),
                ('orignalprice', models.DecimalField(decimal_places=2, default='1', max_digits=8)),
                ('promoteprice', models.DecimalField(decimal_places=2, default='1', max_digits=8)),
                ('stock', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Tmall',
            },
        ),
        migrations.AlterField(
            model_name='shopdetail',
            name='shop_info',
            field=models.OneToOneField(db_column='shop_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tamll.ShopInfo'),
        ),
    ]
