# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-30 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('take_address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'Address',
            },
        ),
    ]
