# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-01 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work51', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCar',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'Shop_car',
            },
        ),
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'Shop_user',
            },
        ),
        migrations.CreateModel(
            name='ShopXq',
            fields=[
                ('xid', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=64)),
                ('brand', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'Shop_XQ',
            },
        ),
        migrations.CreateModel(
            name='ShowProduct',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=64)),
                ('shop_title', models.CharField(max_length=255)),
                ('original_price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('promotion_price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('sales_volume', models.IntegerField()),
                ('count', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
            options={
                'db_table': 'Show_Product',
            },
        ),
        migrations.AddField(
            model_name='shopxq',
            name='sid',
            field=models.OneToOneField(db_column='sid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='work51.ShowProduct'),
        ),
        migrations.AddField(
            model_name='shopcar',
            name='sid',
            field=models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.CASCADE, to='work51.ShowProduct'),
        ),
        migrations.AddField(
            model_name='shopcar',
            name='uid',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='work51.ShopUser'),
        ),
    ]
